title: Janpreet Singh
subtitle: Computer Vision @Umich
description: Website and portfolio of Janpreet Singh, Data Scientist.

author: Janpreet Singh
email: janpreet@umich.edu
avatar: assets/images/avatar.jpg

baseurl: ""
url: "https://janpreetsingh.tech"

# Social settings
facebook_url: https://www.facebook.com/janpreet.singh.756
github_url: https://github.com/janismdhanbad
linkedin_url: https://www.linkedin.com/in/janpreet-singh/
twitter_url: https://twitter.com/janpreetds1

# SEO settiongs
google_analytics: 

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
